### ISSUE TITLE
Failed at the discord-bot-api@0.2.0 start script 'babel-node index'.

### ISSUE THREAD

**Issue by TobiTenno** [simonknittel/discord-bot-api#23]
Failing to start discord-bot-api on npm.

Exact trace:

```
 ~/discord-bot-api $ npm start

> discord-bot-api@0.2.0 start /home/pi/discord-bot-api
> babel-node index

No token provided, and unable to parse 'tenc'. Using login method.
module.js:328
    throw err;
    ^

Error: Cannot find module 'pully'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/discord-bot-api/_plugins/music-bot/index.js:9:14)
    at Module._compile (module.js:398:26)
    at loader (/home/pi/discord-bot-api/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pi/discord-bot-api/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! discord-bot-api@0.2.0 start: `babel-node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-bot-api@0.2.0 start script 'babel-node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-bot-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-bot-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-bot-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/discord-bot-api/npm-debug.log
```

---

I'm assuming that we are supposed to have a babel-node server running to get this working, but it wasn't mentioned in the readme, so it may need to be included or corrected, I don't know which.

**Comment by TobiTenno** [comment]
I forgot to run `npm install` for the music-bot

**Comment by simonknittel** [comment]
It's one of my next step to include some kind of a plugin registry (like npm, bower, etc.) to easily install and remove plugins.

**Comment by simonknittel** [comment]
You can join my server https://discord.gg/0jV29zKlvdJbDx3f if you still have some issues.
